# Server configuration file
# Listen on port 80
listen 80;

# Handler mappings
location /echo EchoHandler{

}

location /static1 StaticHandler {
    root ./data/static1;
}

location /static2 StaticHandler {
    root ./data/static2;
}

location /api ApiHandler {
    data_path ./data/api;
}
location /health HealthHandler {
}