# Server configuration file
# Listen on port 80
listen 80;

# Handler mappings
location /echo echo;

location /static1 static {
    root ./data/static1;
}

location /static2 static {
    root ./data/static2;
}
